spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(kng63WZ9gkAwrkfCz30VI/p24G51DNm/XmT3OotgCAnlH2Fg2IzCP6i51ltgPNSMFjb5Ntc0bU8dDBuiXcJFBYboAVK1/zwV)
    username: ENC(ijcbzqW1EZ2O9YzxPMm8gg==)
    password: ENC(R+XbIS1cbxMAxGr08Ggepg==)

  jpa:
    hibernate:
      ddl-auto: none

    database-platform: org.hibernate.dialect.MySQLDialect


    properties:
      hibernate:
        format_sql: false
        show_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

server:
  port: 8080