spring:
  jasypt:
    encryptor:
      password: ${JASYPT_SECRET_KEY}

  jpa:
    hibernate:
      naming:
        physical-strategy: com.triportreat.backend.common.CustomCamelCaseToUnderscoresNamingStrategy

schedule:
  cron: 0 0 0 * * *
  use: true