spring:
  jasypt:
    encryptor:
      password: ${JASYPT_SECRET_KEY}

  jpa:
    hibernate:
      naming:
        physical-strategy: com.triportreat.backend.common.CustomCamelCaseToUnderscoresNamingStrategy

openapi:
  url: ENC(LLU9kjm25zSyg5yOyVPUXOv+5S90hpA4nf361o39gyCQseJX2RDJrDMSLPujhrq/TCmjv2PKnveaorj78K1640eKP91zTpiwzfJWOl1bB8nQWOJBxaiYZemCEBlBrF0xG5j/N898ydeUWrWl12uuJw==)
  overviewUrl: ENC(fJ2nwclOmMDzWfbtJc+n260rUvkQPCztus0m7PXF8ah2xi8dkwoKWJJWD4J5kQpwhibbqdI2Sk4AYCg3ka/2GVx+zgVOa4H1bhrQhUzOuYr8LCYCKqD2VbYv18Ka3t2d2VMvCUTQMsl9UfOSi2oeYA==)
  key: ENC(D5hw5G8H2Ngep4NJFvgNB0ZWylYDw1+805rEsGA0L6zbbgGshGoKb4OiFtwuUjMW6EH6JYNgwu4G0lW7EZiNZ6bV/C+7KfI157qWMO2dBjvisAVV6VEg7ca0c2zZWXTE9g4Fl5wuwuznQhcZDvTrfw==)

schedule:
  place-data:
    cron: 0 30 2 * * *
  place-views:
    cron: 0 * * * * *
  use: true

