spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(vBkFtshaUZ/2Dd6BWiDqnkZEJaS34NYwXC9eJ/vUO7KUI1YTb4zMm9j7mXDst9SIWlqBlW2MZ9dSfgLVgxGv9O5PoeGd4O8r)
    username: ENC(ijcbzqW1EZ2O9YzxPMm8gg==)
    password: ENC(R+XbIS1cbxMAxGr08Ggepg==)

  jpa:
    hibernate:
      ddl-auto: none

    database-platform: org.hibernate.dialect.MySQLDialect

    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 9090