spring:
  jasypt:
    encryptor:
      password: ${JASYPT_SECRET_KEY}

  jpa:
    hibernate:
      naming:
        physical-strategy: com.triportreat.backend.common.CustomCamelCaseToUnderscoresNamingStrategy

openapi:
  url: ENC(LLU9kjm25zSyg5yOyVPUXOv+5S90hpA4nf361o39gyCQseJX2RDJrDMSLPujhrq/TCmjv2PKnveaorj78K1640eKP91zTpiwzfJWOl1bB8nQWOJBxaiYZemCEBlBrF0xG5j/N898ydeUWrWl12uuJw==)
  key: ENC(D5hw5G8H2Ngep4NJFvgNB0ZWylYDw1+805rEsGA0L6zbbgGshGoKb4OiFtwuUjMW6EH6JYNgwu4G0lW7EZiNZ6bV/C+7KfI157qWMO2dBjvisAVV6VEg7ca0c2zZWXTE9g4Fl5wuwuznQhcZDvTrfw==)
  rows: 1000

schedule:
  cron: 0 0 0 * * *
  use: true

