name: Build and Deploy to EC2

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

env:
  PROJECT_NAME: triportreat_project
  BUCKET_NAME: triportreat-bucket
  CODE_DEPLOY_APP_NAME: triportreat-codedeploy-application
  DEPLOYMENT_GROUP_NAME: triportreat-deploy-group
  JASYPT_SECRET_KEY: ${{ secrets.JASYPT_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./backend"

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Determine branch name
        id: get_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and Test
        run: |
          jarName=$( [ "${{ steps.get_branch.outputs.branch }}" = "main" ] && echo "main" || echo "develop" )
          ./gradlew build -PjarName="$jarName"
        shell: bash

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip  