name: FrontendDeploy

on:
  push:
    branches:
      - CHORE/TOT-53
  pull_request:
    branches:
      - CHORE/TOT-53

env:
  working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Run build
        run: npm run build
        working-directory: ${{ env.working-directory }}

      - name: Configure AWS credentials
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 sync ./build s3://triportreat-front-bucket --profile triportreat-user
        working-directory: ${{ env.working-directory }}
