SET REFERENTIAL_INTEGRITY FALSE;
-- truncate table "REGION";
truncate table "USER";
truncate table "PLAN_REGION";
truncate table "PLAN";
SET REFERENTIAL_INTEGRITY TRUE;

-- ALTER TABLE "REGION" ALTER COLUMN id RESTART WITH 1;
ALTER TABLE "USER" ALTER COLUMN id RESTART WITH 1;
ALTER TABLE "PLAN_REGION" ALTER COLUMN id RESTART WITH 1;
ALTER TABLE "PLAN" ALTER COLUMN id RESTART WITH 1;
